version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      documentation:
        patterns:
          - "mkdocs*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: pip
    directory: /labs/aws/01-cloud-architecture-ticketing
    schedule:
      interval: monthly
    groups:
      ticketing-lab:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /labs/aws/01-cloud-architecture-ticketing
    schedule:
      interval: monthly
